<?php
/**
 * @file
 * testimonial_content_.features.inc
 */

/**
 * Implements hook_node_info().
 */
function testimonial_content__node_info() {
  $items = array(
    'testimonials' => array(
      'name' => t('Testimonials'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
